### ISSUE TITLE
Encouragement for users not to day 100 yet

### ISSUE THREAD

**Issue by mathewmorris** [freeCodeCamp/100DaysOfCode-twitter-bot#50]
What if we had something to where the bot would encourage someone to continue their 100DaysofCode? Maybe if they haven't posted in 7+ days and haven't posted Day 100 they would get a tweet mention that encouraged them to keep on going??

**Comment by spences10** [comment]
Hi @mathewmorris, this is a good suggestion, is this something you could take on?

I have used a `LevelDB` integration for the user blacklist so that users are not sent tweets encouraging them  more than once every 24hrs you could expand on this to include the users on the #100DoC hashtag

What I added was quite crude but does the job, I do want to further enhance this though and this could be a good opportunity [for you] to get involved :+1:

**Comment by harmonicadan** [comment]
I only heard about it today .... can I still start it ?

**Comment by amandeepmittal** [comment]
@harmonicadan are you interested in taking part in the challenge? Of course you can. If you want to contribute to this repo check out the issues.

**Comment by spences10** [comment]
This would be a great opportunity for someone to set up some kind of backend (and all the fun that comes with that) to track users and their tweets to the #100DaysOfCode hashtag.

There would be a need to function to do a daily/weekly check for users that are in there, I'm not sure how much volume there would be going to the database as there'd need to be a record for each time someone tweets with the hashtag, or a timestamp against their userid when they last tweeted to the hashtag
